config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	devise_scope :user do
    	get 'users/sign_out' => "devise/sessions#destroy"
	end

	resources :queries do
		resources :results
	end
  resources :queries

  resources :results do
    resources :favourites
  end
  resources :favourites

  namespace :admin do
    resources :users do
      #view for confirmation before deletion
      get "delete"
    end
    resources :dashboards
    root 'dashboards#index'
  end

	root 'queries#index'

   #404 page. comment this to see the routing errors
   get "*any", via: :all, to: "errors#not_found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  has_one :result
end

app/models/popular_product.rb
class PopularProduct < ApplicationRecord
end

app/models/query.rb
class Query < ApplicationRecord

  belongs_to :user, optional: true
  
  validates :name, presence: true

  has_many :result
  has_many :seller_detail
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :query
  has_one :favourite
end

app/models/seller_detail.rb
class SellerDetail < ApplicationRecord
  belongs_to :query
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favourite
  has_many :query

  validates :name, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :ensure_admin_user!

	def home
	end

	private
	def ensure_admin_user!
		unless current_user and current_user.admin?
			flash[:alert] = "You don't have sufficient credentials to access this page."
			redirect_to root_path
		end
	end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :ensure_admin_user!

	def home
	end

	def ensure_admin_user!
		unless current_user and current_user.admin?
			flash[:alert] = "You don't have sufficient credentials to access this page."
			redirect_to root_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?
	layout "front" 

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name) }
		devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :ensure_user!
  layout "front"

  def index
    favourites = Favourite.where(user_id: current_user.id)

    @favourites = []
    keys = [:id, :result_id, :name, :price, :platform, :img, :url]

    favourites.each do |favourite|
      result = Result.find(favourite.result_id)
      result_id = favourite.result_id
      # next if result.url == nil
      fav = Hash[keys.map {|x| [x,1]}]
      fav[:id] = result.id
      fav[:result_id] = result_id
      fav[:name] = result.name
      fav[:price] = result.price
      fav[:platform] = result.platform
      fav[:img] = result.img
      fav[:url] = result.url
      @favourites << fav
    end

    JSON.pretty_generate(@favourites)
  end

  def create
    if current_user
      item = Result.find_by(name: params[:result_id])

      # Update favourited attribute boolean value to be true when a search result is added to favourites
      item.update(favourited: true)

      favourite = Favourite.create(user_id: current_user.id, result_id: item.id)
      favourite.save
    else
      redirect_to user_session_path
    end
  end

  def destroy
    favourite_id = Favourite.find_by(result_id: params[:result_id]).id
    puts "Id to be deleted => #{favourite_id}"

    item = Result.find(params[:result_id])
    item.update(favourited: false)

    Favourite.destroy(favourite_id)
    redirect_to result_favourites_path
  end

  private
	def query_params
		params.permit(:name)
	end

  def ensure_user!
    unless current_user
      flash[:alert] = "You don't have sufficient credentials to access this page."
      redirect_to root_path
    end
  end
end

app/controllers/queries_controller.rb
require 'masterScrapper'

class QueriesController < ApplicationController
	before_action :authenticate_user!, :except => [ :index, :create, :account]
	layout "front"

	#search page
	def index
	end

	def new
		@query = Query.new
	end

	def create
		if params[:name] == ""
			flash[:notice] = "You have not entered a search query"
			return redirect_to queries_path
		end

		params[:name].downcase!

		# Query exists in the database
		if Query.find_by(name: params[:name])
			@query = Query.new
			@query.name = params[:name]
			searched_query = Query.find_by(name: params[:name])
			parsedQoo10 = Result.where(platform: 'Qoo10', query_id: searched_query.id)
			parsedLazada = Result.where(platform: 'Lazada', query_id: searched_query.id)
			parsedCarousell = Result.where(platform: 'Carousell', query_id: searched_query.id)
			@parsedAll = [{platform:'Qoo10',results:parsedQoo10},{platform:'Lazada',results:parsedLazada},{platform:'Carousell',results:parsedCarousell}]
		# Query does not exist in the database
		else
			@query = Query.new(query_params)
			@query.user_id = current_user.id if current_user
			@query.save!
			scrap = MasterScrapper.new(@query)
			@parsedAll = scrap.generate
		end
	end

	private
	def query_params
		current_user ? (params.permit(:name, current_user.id)) : (params.permit(:name))
	end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
	        when 'notice' then "alert alert-dismissable alert-info"
	        when 'success' then "alert alert-dismissable alert-success"
	        when 'error' then "alert alert-dismissable alert-danger"
	        when 'alert' then "alert alert-dismissable alert-danger"
	    end
	end

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def  devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    if resource.errors.full_messages.any?
        flash.now[:error] = resource.errors.full_messages
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/favourites/index.html.erb
<div class="container index-wrapper">
  <h1><%= current_user.name %>'s favourites</h1>
  <div class="row">
    <% @favourites.each do |favourite| %>
    <!-- Card -->
    <div class="col-md-3 fav_card-container">
      <div class="card-flip">
        <!-- Card Front -->
        <div class="card front card-inverse fav_card">
          <img class="card-img object-fit" src= <%= favourite[:img] %> alt="Card image" width="250" height="250">
          <div class="card-img-overlay">
            <h4 class="card-title results_ellipsis fav_text"><%= favourite[:name] %></h4>
          </div>
        </div>
        <!-- End Card Front -->

        <!-- Card Back -->
        <div class="card back fav_card ">
          <div class="card-block">
            <div class="fav_backCardText">
              <h5 class="card-title"><%= favourite[:name] %></h5>
              <h6 class="card-subtitle mb-2 text-muted">
                <strong>Price:</strong><%= favourite[:price] %>
                <p><strong>Platform:</strong><%= favourite[:platform] %></p>
              </h6>
            </div>
            <div class="fav_buttons">
              <a href= <%= favourite[:url] %> class="btn btn-outline-dark">Buy Now</a>
              <%= link_to 'Unfavourite', result_favourite_path(favourite), :remote => true, method: :delete, class: "btn btn-outline-dark" %>
            </div>
          </div>
        </div>
        <!-- End Card Back -->
      </div>
    </div>
    <!-- End Card -->
    <% end %>
  </div>
</div>

<div id="results"></div>

<script>
  $( "form" ).submit(function( ) {
    $("#navbar_loader").addClass( "onclic");
    $("#navbar_submit")[0].style.display = "none";
    $("#navbar_loader")[0].style.display = "block";
    $(".index-wrapper")[0].style.display = "none";
  });
</script>

app/views/queries/_account.html.erb
<% if user_signed_in? %>
<% else %>
<div class="account_container">
	<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'account_form', id:'account_signUp'}) do |f| %>
		<%= devise_error_messages! %>  	
		<h3 class="account_header">Create Your Account</h3>
		<p class="account_text">Connect with us today.</p>
		<%= f.email_field :email, autofocus: true, class:"w100 account_input", placeholder: "Your Email",id:"account_signUp_email" %>
		<%= f.text_field :name, autofocus: true,class:"account_input", placeholder: "Your Name" %>
		<%= f.password_field :password, autocomplete: "off", class:"account_input", placeholder: "Insert Password",id:"account_signUp_pass" %>
		<%= f.password_field :password_confirmation, autocomplete: "off", class:"account_input", placeholder: "Verify Password" %>
		<button class="form-btn sx log-in account_button" type="button">Log In</button>
		<%= f.submit "Register", class:"form-btn dx account_button" %>
	<% end %>
	<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'account_form', id:'account_signIn'}) do |f| %>
		<h3 class="account_header">Welcome</br>Back !</h3>
		<%= f.email_field :email, autofocus: true, class:"w100 account_input", placeholder:"Your Email",id:"account_signIn_email"%>
		<%= f.password_field :password, autocomplete: "off", class:"account_input", placeholder:"Your Password",id:"account_signIn_pass" %>			
		<button class="form-btn sx account_back account_button" type="button">Back</button>
		<%= f.submit "Log in", class:"form-btn dx account_button" %>
	<% end %>		
</div>
<% end %>

app/views/queries/_show.html.erb
<div class="container">
    <% @parsedAll.each do |site| %>
    <div class="platform-title results_platform">
        <br>
        <% if site[:platform] == "Qoo10" %>
            <%= image_tag 'Qoo10.png', height: '80', width: '220', class:"results_title" %>
        <% elsif site[:platform] == "Lazada" %>
            <%= image_tag 'lazada.png', height: '100', width: '250', class:"results_title" %>
        <% elsif site[:platform] == "Carousell" %>
            <%= image_tag 'carousell.png', height: '80', width: '400', class:"results_title" %>
        <% end %>
        <br><br>
    </div>
    <div class="row mb-3">
        <% site[:results].each do |item| %>
        <div class="col-md-6">
            <div class="d-flex flex-row border rounded results_card">
                <div class="p-0 w-25">
                    <img class="object-fit" src= <%= item["img"] %> width="150" height="150"/>
                </div>
                <div class="pl-3 pt-2 pr-2 pb-2 w-75 border-left results_cardBody">
                    <h4 class="results_ellipsis results_name" ><%= item.name %></h4>
                    <h5 class="text-info results_price"><%= item.price %></h5>
                    <div class = "results_buttons">
                        <p class="text-right m-0">
                            <% if item.favourited %>
                            <% else %>
                                <%= link_to 'Favourite', result_favourites_path(item.name), method: :post, class: "btn btn-dark", id: item.name, :onclick => "toggle_fav_bt(this.id)" %>
                            <% end %>
                            <a href=<%= item["url"] %> target=”_blank” class="btn btn-dark"><i class="fas fa-shopping-cart"></i> View More</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
    <% end %>
</div>


<!-- JavaScript logic to make add to favourite button disappear once clicked... -->
<script type="text/javascript">
  function toggle_fav_bt(clicked_id) {
    document.getElementById(clicked_id).style.display = "none";
  }
</script>

app/views/queries/index.html.erb
<div class="index-wrapper">
  <div class="container-fluid">
    <p class="h1">Supporting Platforms</p>
    <%= image_tag 'Qoo10.png', height: '40', width: '100' %>
    <%= image_tag 'lazada.png', height: '30', width: '80' %>
    <%= image_tag 'carousell.png', height: '30', width: '150' %>
  </div>
  <%= render "queries/account" %>
</div>

<div id="results"></div>

<script type="text/javascript">
  $( "form" ).submit(function( ) {
    $("#navbar_loader").addClass( "onclic");
    $("#navbar_submit")[0].style.display = "none";
    $("#navbar_loader")[0].style.display = "block";
    $(".index-wrapper")[0].style.display = "none";
  });

  $(".log-in").click(function(){
    $("#account_signIn").addClass("active-dx");
    $("#account_signUp").addClass("inactive-sx");
    $("#account_signUp").removeClass("active-sx");
    $("#account_signIn").removeClass("inactive-dx");
  });

  $(".account_back").click(function(){
    $("#account_signUp").addClass("active-sx");
    $("#account_signIn").addClass("inactive-dx");
    $("#account_signIn").removeClass("active-dx");
    $("#account_signUp").removeClass("inactive-sx");
  });
</script>

app/views/queries/show.html.erb
<!-- 
############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
Qoo10 -->
<div class="main-wrapper">
	<div class="container d-flex justify-content-around">
		<div class="card-deck-wrapper view d-flex flex-wrap">
			<div class="platform-title">
				<br>
				<%= image_tag 'Qoo10.png', height: '80', width: '220' %>
				<br><br>
			</div>
			<div class="card-deck justify-content-around">

				<div class="card col-mb-4">
					<div class="view overlay">
						<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg" alt="Card image cap">
						<a href="#!">
							<div class="mask rgba-white-slight"></div>
						</a>
					</div>
					<div class="card-body">
						<h4 class="card-title"><%= @query.name %></h4>
						<p class="card-text">
							<strong>Price:</strong>

						</p>
						<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
						<% if @logged_in ==true %>
						<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
						<% end %>
					</div>
				</div>

				<div class="card col-mb-4">
					<div class="view overlay">
						<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/14.jpg" alt="Card image cap">
						<a href="#!">
							<div class="mask rgba-white-slight"></div>
						</a>
					</div>
					<div class="card-body">
						<h4 class="card-title"><%= @query.name %></h4>
						<p class="card-text">
							<strong>Price:</strong>
							some price $123
						</p>
						<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
						<% if @logged_in ==true %>
						<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
						<% end %>
					</div>
				</div>

				<div class="card col-mb-4">
					<div class="view overlay">
						<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/15.jpg" alt="Card image cap">
						<a href="#!">
							<div class="mask rgba-white-slight"></div>
						</a>
					</div>
					<div class="card-body">
						<h4 class="card-title"><%= @query.name %></h4>
						<p class="card-text">
							<strong>Price:</strong>
							some price $123
						</p>
						<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
						<% if @logged_in ==true %>
						<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
						<% end %>
					</div>
				</div>
			</div>
			<div class="next-three">
				<button type="button" class="next-btn btn btn-light-blue btn-md">View next three</button>
			</div>
		</div>
	</div>






	<br><br>

<!-- 
	#########################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
	Lazada -->
	<div class="container d-flex justify-content-around">
		<div class="row">
			<div class="col">
				<div class="card-deck-wrapper view">
					<div class="platform-title">
						<br>
						<%= image_tag 'lazada.png', height: '100', width: '250' %>
						<br><br>
					</div>
					<div class="card-deck d-flex justify-content-around">

						<div class="card col-mb-4">
							<div class="view overlay">
								<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg" alt="Card image cap">
								<a href="#!">
									<div class="mask rgba-white-slight"></div>
								</a>
							</div>
							<div class="card-body">
								<h4 class="card-title"><%= @query.name %></h4>
								<p class="card-text">
									<strong>Price:</strong>
									some price $123
								</p>
								<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
								<% if @logged_in ==true %>
								<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
								<% end %>
							</div>
						</div>

						<div class="card col-mb-4">
							<div class="view overlay">
								<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/14.jpg" alt="Card image cap">
								<a href="#!">
									<div class="mask rgba-white-slight"></div>
								</a>
							</div>
							<div class="card-body">
								<h4 class="card-title"><%= @query.name %></h4>
								<p class="card-text">
									<strong>Price:</strong>
									some price $123
								</p>
								<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
								<% if @logged_in ==true %>
								<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
								<% end %>
							</div>
						</div>

						<div class="card col-mb-4">
							<div class="view overlay">
								<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/15.jpg" alt="Card image cap">
								<a href="#!">
									<div class="mask rgba-white-slight"></div>
								</a>
							</div>
							<div class="card-body">
								<h4 class="card-title"><%= @query.name %></h4>
								<p class="card-text">
									<strong>Price:</strong>
									some price $123
								</p>
								<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
								<% if @logged_in ==true %>
								<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
								<% end %>
							</div>
						</div>
					</div>
					<div class="next-three">
						<button type="button" class="next-btn btn btn-light-blue btn-md">View next three</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br><br>


<!-- 
############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
Shopee -->
<div class="container d-flex justify-content-around">
	<div class="row">
		<div class="col">
			<div class="card-deck-wrapper view">
				<div class="platform-title">
					<br>
					<%= image_tag 'carousell.png', height: '80', width: '400' %>
					<br><br>
				</div>
				<div class="card-deck d-flex justify-content-around">

					<div class="card col-mb-4">
						<div class="view overlay">
							<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg" alt="Card image cap">
							<a href="#!">
								<div class="mask rgba-white-slight"></div>
							</a>
						</div>
						<div class="card-body">
							<h4 class="card-title"><%= @query.name %></h4>
							<p class="card-text">
								<strong>Price:</strong>
								some price $123
							</p>
							<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
							<% if @logged_in ==true %>
							<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
							<% end %>
						</div>
					</div>

					<div class="card col-mb-4">
						<div class="view overlay">
							<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/14.jpg" alt="Card image cap">
							<a href="#!">
								<div class="mask rgba-white-slight"></div>
							</a>
						</div>
						<div class="card-body">
							<h4 class="card-title"><%= @query.name %></h4>
							<p class="card-text">
								<strong>Price:</strong>
								some price $123
							</p>
							<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
							<% if @logged_in ==true %>
							<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
							<% end %>
						</div>
					</div>

					<div class="card col-mb-4">
						<div class="view overlay">
							<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/15.jpg" alt="Card image cap">
							<a href="#!">
								<div class="mask rgba-white-slight"></div>
							</a>
						</div>
						<div class="card-body">
							<h4 class="card-title"><%= @query.name %></h4>
							<p class="card-text">
								<strong>Price:</strong>
								some price $123
							</p>
							<button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
							<% if @logged_in ==true %>
							<button type="button" class="btn btn-yellow btn-md">Add to favourites</button>
							<% end %>
						</div>
					</div>
				</div>
				<div class="next-three">
					<button type="button" class="next-btn btn btn-light-blue btn-md"><strong>View next three</strong></button>
				</div>
			</div>
		</div>
	</div>
</div>
</div>