config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	devise_scope :user do
    	get 'users/sign_out' => "devise/sessions#destroy"
	end

	resources :queries do
		resources :results
	end
  resources :queries

  resources :results do
    resources :favourites
  end
  resources :favourites

  namespace :admin do
    resources :users do
      #view for confirmation before deletion
      get "delete"
    end
    resources :dashboards
    root 'dashboards#index'
  end

	root 'queries#index'

   #404 page. comment this to see the routing errors
   get "*any", via: :all, to: "errors#not_found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  has_one :result
end

app/models/popular_product.rb
class PopularProduct < ApplicationRecord
end

app/models/query.rb
class Query < ApplicationRecord

  belongs_to :user, optional: true
  
  validates :name, presence: true

  has_many :result
  has_many :seller_detail
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :query
  has_one :favourite
end

app/models/seller_detail.rb
class SellerDetail < ApplicationRecord
  belongs_to :query
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favourite
  has_many :query

  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	layout "admin" 
	
	def index
		@users = User.all	
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@users = User.all
		@user = User.create(user_params)
	end	

	def update
		@users = User.all
		@user = User.find(params[:id])
		if params[:user][:password].blank?
		  params[:user].delete(:password)
		  params[:user].delete(:password_confirmation)
		end

		@user.update_attributes(user_params)
	end

  	def delete
   		@user = User.find(params[:user_id])
  	end

  	def destroy
  		@users = User.all
    	@user = User.find(params[:id])
    	@user.destroy
  	end

	private
  	def user_params
    	params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :ensure_admin_user!

	def home
	end

	private
	def ensure_admin_user!
		unless current_user and current_user.admin?
			flash[:alert] = "You don't have sufficient credentials to access this page."
			redirect_to root_path
		end
	end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :ensure_admin_user!

	def home
	end

	def ensure_admin_user!
		unless current_user and current_user.admin?
			flash[:alert] = "You don't have sufficient credentials to access this page."
			redirect_to root_path
		end
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :ensure_user!
  layout "front"

  def index
    favourites = Favourite.where(user_id: current_user.id)

    @favourites = []
    keys = [:id, :result_id, :name, :price, :platform, :img, :url]

    favourites.each do |favourite|
      result = Result.find(favourite.result_id)
      result_id = favourite.result_id
      # next if result.url == nil
      fav = Hash[keys.map {|x| [x,1]}]
      fav[:id] = result.id
      fav[:result_id] = result_id
      fav[:name] = result.name
      fav[:price] = result.price
      fav[:platform] = result.platform
      fav[:img] = result.img
      fav[:url] = result.url
      @favourites << fav
    end

    JSON.pretty_generate(@favourites)
  end

  def create
    if current_user
      item = Result.find_by(name: params[:result_id])

      # Update favourited attribute boolean value to be true when a search result is added to favourites
      item.update(favourited: true)

      favourite = Favourite.create(user_id: current_user.id, result_id: item.id)
      favourite.save
    else
      redirect_to user_session_path
    end
  end

  def destroy
    favourite_id = Favourite.find_by(result_id: params[:result_id]).id
    puts "Id to be deleted => #{favourite_id}"

    item = Result.find(params[:result_id])
    item.update(favourited: false)

    Favourite.destroy(favourite_id)
    redirect_to result_favourites_path
  end

  private
	def query_params
		params.permit(:name)
	end

  def ensure_user!
    unless current_user
      flash[:alert] = "You don't have sufficient credentials to access this page."
      redirect_to root_path
    end
  end
end

app/controllers/queries_controller.rb
require 'masterScrapper'

class QueriesController < ApplicationController
	before_action :authenticate_user!, :except => [ :index, :create, :account]
	layout "front"

	#search page
	def index
	end

	def new
		@query = Query.new
	end

	def create
		if params[:name] == ""
			flash[:notice] = "You have not entered a search query"
			return redirect_to queries_path
		end

		params[:name].downcase!

		# Query exists in the database
		if Query.find_by(name: params[:name])
			@query = Query.new
			@query.name = params[:name]
			searched_query = Query.find_by(name: params[:name])
			parsedQoo10 = Result.where(platform: 'Qoo10', query_id: searched_query.id)
			parsedLazada = Result.where(platform: 'Lazada', query_id: searched_query.id)
			parsedCarousell = Result.where(platform: 'Carousell', query_id: searched_query.id)
			@parsedAll = [{platform:'Qoo10',results:parsedQoo10},{platform:'Lazada',results:parsedLazada},{platform:'Carousell',results:parsedCarousell}]
		# Query does not exist in the database
		else
			@query = Query.new(query_params)
			@query.user_id = current_user.id if current_user
			@query.save!
			scrap = MasterScrapper.new(@query)
			@parsedAll = scrap.generate
		end
	end

	private
	def query_params
		current_user ? (params.permit(:name, current_user.id)) : (params.permit(:name))
	end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
	        when 'notice' then "alert alert-dismissable alert-info"
	        when 'success' then "alert alert-dismissable alert-success"
	        when 'error' then "alert alert-dismissable alert-danger"
	        when 'alert' then "alert alert-dismissable alert-danger"
	    end
	end

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def  devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    if resource.errors.full_messages.any?
        flash.now[:error] = resource.errors.full_messages
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/admin/users/_delete.html.erb
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h3>Deletion</h3>
    </div>
    <div class="modal-body">
    <ul class="errors"></ul>
        Are you sure you wish to delete <b><%= @user.name %></b>?
    </div>
    <div class="modal-footer">
    <%= link_to "Yes", admin_user_path(@user), method: :delete, remote: true, class: "btn btn-danger" %>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
    </div>
    </div>
</div>

app/views/admin/users/_edit.html.erb
<div class="modal-dialog">
	<div class="modal-content">
	<div class="modal-header">
		<h3 class="modal-title"><%= "Editing #{@user.name}" %></h3>
	</div>
	<%= form_for @user, url: admin_user_path(@user), remote: true, html: { style: "display:inline;" } do |f| %>
	<div class="modal-body">
		<ul class="errors"></ul>
		<div class="form-group">
     		<label class="bmd-label-floating">Name</label>
     		<%= f.text_field :name, class: "form-control" %>
  		</div>
		<div class="form-group">
			<label class="bmd-label-floating">Email</label>
			<%= f.text_field :email, class: "form-control" %>
		</div>
		<div class="form-check">
		    <label class="form-check-label">
		    	Admin status: 
		        <%= f.check_box :admin, class: "form-check-input" %> 
		        <span class="form-check-sign">
		            <span class="check"></span>
		        </span>
		    </label>
		</div>		
	</div>
	<div class="modal-footer">
		<%= f.submit class: "btn btn-primary" %>
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	</div>
	<% end %>
	</div>
</div>

app/views/admin/users/_index.html.erb
<% @users.each do |user| %>
	  <tr>
	    <td><%= user.name %></td>
	    <td><%= user.email %></td>
	    <td><%= user.admin %></td>
	    <td><%= user.last_sign_in_at %></td>
	    <td><%= user.created_at %></td>
	    <td><%= link_to "Edit", edit_admin_user_path(user.id),remote: true, class: "btn btn-success" %>
	    	<%= link_to "Delete", admin_user_delete_path(user.id), remote: true, class: "btn btn-danger" %>
	    </td>
	  </tr>
<% end %>

  

app/views/admin/users/_new.html.erb
<div class="modal-dialog">
<div class="modal-content">
    <div class="modal-header">
        <h3>Adding new user</h3>
    </div>
    <%= form_for @user, url: admin_users_path, remote: true, html: { style: "display:inline;" } do |f| %>
    <div class="modal-body">
        <ul class="errors"></ul>
        <div class="form-group">
            <label class="bmd-label-floating">Name</label>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <label class="bmd-label-floating">Email</label>
            <%= f.text_field :email, class: "form-control" %>
        </div> 
        <div class="form-group">
            <label class="bmd-label-floating">Password</label>
            <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
        <div>
            <label class="bmd-label-floating">Confirm Password</label>
            <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                Admin status: 
                <%= f.check_box :admin, class: "form-check-input" %> 
                <span class="form-check-sign">
                    <span class="check"></span>
                </span>
            </label>
        </div> 
    </div>
    <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
    <% end %>
    </div>
</div>

app/views/admin/users/_save.js.erb
$("ul.errors").html("")
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".user-index").html("<%= escape_javascript(render 'index') %>")
  $("#user-modal").modal("hide")
<% end %>

app/views/admin/users/create.js.erb
<%= render "save" %>

app/views/admin/users/delete.js.erb
$("#user-modal").html("<%= escape_javascript(render 'delete') %>")
$("#user-modal").modal("show")

app/views/admin/users/destroy.js.erb
<%= render "save" %>

app/views/admin/users/edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit') %>")
$("#user-modal").modal("show")

app/views/admin/users/index.html.erb
<div class="wrapper">
  <div class="sidebar" data-color="orange">
    <div class="logo">
      <h2 class="simple-text">ADMIN</h2>
    </div>
    <div class="sidebar-wrapper">
      <ul class="nav">
        <li>
          <a href="/">
            <i class="material-icons">exit_to_app</i>
            <p>Exit Admin</p>
          </a>
        </li>
        <li>
          <a href="/admin">
            <i class="material-icons">dashboard</i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="active">
          <a href="/admin/users">
            <i class="material-icons">content_paste</i>
            <p>Manage Users</p>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="main-panel">
    <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute fixed-top">
      <div class="container-fluid">
        <div class="navbar-wrapper">
          <h1 class="navbar-brand">Manage Users</h1>
        </div>
      </div>
    </nav>
    <div class="content">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header" id="userCardTable">
            <h4 class="card-title">Registered users</h4>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover table-striped">
              <thead class="text-warning">
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Admin</th>
                  <th>Last login</th>
                  <th>Date created</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody class="user-index">
                <%= render "index" %>
              </tbody>
            </table>
          </div>
        </div>
        <div id="user-modal" class="modal fade"></div>
        <%= link_to "Add new user", new_admin_user_path, remote: true, class: "btn btn-warning"%>
      </div>
    </div>
  </div>

app/views/admin/users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new') %>")
$("#user-modal").modal("show")

app/views/admin/users/update.js.erb
<%= render "save" %>

app/views/users/admin.html.erb
<br><br><br><br>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-5 offset-1 chart">
        <canvas id="sellerChart"></canvas>
      </div>
      <div class="col-lg-5 chart">
        <canvas id="topProductChart"></canvas>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-5 offset-1 chart">
        <canvas id="averagePriceChart"></canvas>
      </div>
      <div class="col-lg-5 chart">
        <canvas id="#"></canvas>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 offset-2 chart">
        <canvas id="#"></canvas>
      </div>
      <div class="col-lg-4 chart">
        <canvas id="#"></canvas>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 offset-2 chart">
        <canvas id="#"></canvas>
      </div>
      <div class="col-lg-4 chart">
        <canvas id="#"></canvas>
      </div>
    </div>
  </div>



















  <script>


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Number of sellers

let sellerChart = document.getElementById('sellerChart').getContext('2d');

    // Global Options
    Chart.defaults.global.defaultFontFamily = 'Lato';
    Chart.defaults.global.defaultFontSize = 18;
    Chart.defaults.global.defaultFontColor = '#777';
    Chart.defaults.global.animation.duration = 1500;

    let myChartOne = new Chart(sellerChart, {
      type:'pie', // bar, horizontalBar, pie, line, doughnut, radar, polarArea
      data:{
        labels:['Qoo10', 'Shopee', 'Lazada'],
        datasets:[{
          label:'Sellers',
          data:[
          617594,
          181045,
          95072
          ],
          //backgroundColor:'green',
          backgroundColor:[
          'rgba(255, 99, 132, 0.6)',
          'rgba(54, 162, 235, 0.6)',
          'rgba(255, 206, 86, 0.6)'
          ],
          borderWidth:1,
          borderColor:'#777',
          hoverBorderWidth:3,
          hoverBorderColor:'#000'
        }]
      },
      options:{
        title:{
          display:true,
          text:'Number of items in each platform',
          fontSize:25
        },
        legend:{
          display:true,
          position:'right',
          labels:{
            fontColor:'#000'
          }
        },
        layout:{
          padding:{
            left:50,
            right:0,
            bottom:0,
            top:0
          }
        },
        tooltips:{
          enabled:true
        }
      }
    });


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Average discounts

let topProductChart = document.getElementById('topProductChart').getContext('2d');

    // Global Options
    Chart.defaults.global.defaultFontFamily = 'Lato';
    Chart.defaults.global.defaultFontSize = 18;
    Chart.defaults.global.defaultFontColor = '#777';

    let myChartTwo = new Chart(topProductChart, {
      type:'horizontalBar', // bar, horizontalBar, pie, line, doughnut, radar, polarArea
      data:{
        labels:['Qoo10', 'Shopee', 'Lazada'],
        datasets:[{
          label:'in %',
          data:[
          12,
          14,
          25
          ],
          //backgroundColor:'green',
          backgroundColor:[
          'rgba(255, 99, 132, 0.6)',
          'rgba(54, 162, 235, 0.6)',
          'rgba(255, 206, 86, 0.6)'
          ],
          borderWidth:1,
          borderColor:'#777',
          hoverBorderWidth:3,
          hoverBorderColor:'#000'
        }]
      },
      options:{
        scales: {
          xAxes: [{
            ticks: {
              min:0,
              max:100
            }
          }]
        },
        title:{
          display:true,
          text:'Average discounts (in %)',
          fontSize:25
        },
        legend:{
          display:false,
          position:'right',
          labels:{
            fontColor:'#000'
          }
        },
        layout:{
          padding:{
            left:50,
            right:0,
            bottom:0,
            top:0
          }
        },
        tooltips:{
          enabled:true
        }
      }
    });


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Average price

let averagePriceChart = document.getElementById('averagePriceChart').getContext('2d');

    // Global Options
    Chart.defaults.global.defaultFontFamily = 'Lato';
    Chart.defaults.global.defaultFontSize = 18;
    Chart.defaults.global.defaultFontColor = '#777';

    let myChartThree = new Chart(averagePriceChart, {
      type:'bar', // bar, horizontalBar, pie, line, doughnut, radar, polarArea
      data:{
        labels:['Qoo10', 'Shopee', 'Lazada'],
        datasets:[{
          label:'in $',
          data:[
          1943,
          1743,
          2512
          ],
          //backgroundColor:'green',
          backgroundColor:[
          'rgba(255, 99, 132, 0.6)',
          'rgba(54, 162, 235, 0.6)',
          'rgba(255, 206, 86, 0.6)'
          ],
          borderWidth:1,
          borderColor:'#777',
          hoverBorderWidth:3,
          hoverBorderColor:'#000'
        }]
      },
      options:{
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        },
        title:{
          display:true,
          text:'Average price (in $)',
          fontSize:25
        },
        legend:{
          display:false,
          position:'right',
          labels:{
            fontColor:'#000'
          }
        },
        layout:{
          padding:{
            left:50,
            right:0,
            bottom:0,
            top:0
          }
        },
        tooltips:{
          enabled:true
        }
      }
    });


  </script>
</body>
</html>

app/views/users/login.html.erb
<form action="#">
	<div class="container">
		<div class="row form-group">
			<div class="col-lg-6 offset-3 sign-up-form">
				<br>
				<p class="login text-center">LOGIN</p>

				<!-- Material input email -->
				<div class="login-form">
					<div class="md-form">


						<i class="fa fa-envelope prefix amber-text"></i>
						<input type="email" id="materialFormRegisterEmailEx" class="form-control">
						<label for="materialFormRegisterEmailEx">Your email</label>


					</div>

					<!-- Material input password -->
					<div class="md-form">
						<div>
							<i class="fa fa-lock prefix amber-text"></i>
							<input type="password" id="materialFormRegisterPasswordEx" class="form-control">
							<label for="materialFormRegisterPasswordEx">Your password</label>
						</div>
					</div>

					<div class="text-center mt-4">
						<button class="btn-login" type="submit">LOGIN</button>
					</div>
					<br>
					<h4>
						Don't have an account?
						<a href="/sign-up"><strong class="orange">Sign up</strong></a>
					</h4>
					<br>
				</div>
				
			</div>
		</div>
	</div>
</form>

app/views/users/new.html.erb
<form action="#">
	<div class="container">
		<div class="row form-group">
			<div class="col-lg-6 offset-3 sign-up-form">
				<br>
				<p class="h4 text-center login">SIGN UP</p>

				<div class="login-form">
					<div class="md-form">
						<i class="fa fa-user prefix amber-text"></i>
						<input type="text" id="materialFormRegisterNameEx" class="form-control">
						<label for="materialFormRegisterNameEx">Your name</label>
					</div>

					<!-- Material input email -->
					<div class="md-form">
						<i class="fa fa-envelope prefix amber-text"></i>
						<input type="email" id="materialFormRegisterEmailEx" class="form-control">
						<label for="materialFormRegisterEmailEx">Your email</label>
					</div>

					<!-- Material input email -->
					<div class="md-form">
						<i class="fa fa-exclamation-triangle prefix amber-text"></i>
						<input type="email" id="materialFormRegisterConfirmEx" class="form-control">
						<label for="materialFormRegisterConfirmEx">Confirm your email</label>
					</div>

					<!-- Material input password -->
					<div class="md-form">
						<i class="fa fa-lock prefix amber-text"></i>
						<input type="password" id="materialFormRegisterPasswordEx" class="form-control">
						<label for="materialFormRegisterPasswordEx">Your password</label>
					</div>

					<div class="text-center mt-4">
						<button class="btn-login" type="submit">Register</button>
					</div>
					<br>
					<h4>
						Already an user?
						<a href="/log-in"><strong class="orange">Login</strong></a>
					</h4>
					<br>
					
				</div>
				<!-- Material input text -->
				
			</div>
		</div>
	</div>
</form>

app/views/users/profile.html.erb
<br><br><br><br>
<div class="container view">
    <div class="row">
        <div class="col-lg-12">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs nav-justified">
                <li class="nav-item">
                    <a class="nav-link profile-tab" data-toggle="tab" href="#panel1" role="tab">PROFILE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link favourites-tab" data-toggle="tab" href="#panel2" role="tab">FAVOURITES</a>
                </li>
            </ul>
            <br>
            
            <!-- Tab panels -->
            <div class="tab-content card">
                <!--Panel 1-->
                <div class="tab-pane fade in show active" id="panel1" role="tabpanel">
                    <h4 class="profile-items">
                        Tom Dick Harry <br>
                        someemail@gmail.com
                        <br><br>
                        <button type="button" class="btn btn-yellow btn-md"><strong>EDIT</strong></button>
                    </h4>
                    <div class="row">
                        <div class="col-lg-10 offset-1 chart">
                            <canvas id="sellerChart"></canvas>
                        </div>
                    </div>
                </div>

                
                <br>
                <!--/.Panel 1-->
                <!--Panel 2-->
                <div class="tab-pane fade" id="panel2" role="tabpanel">
                    <br>
                    <div class="favourites-wrapper">
                        <div class="container test d-flex justify-content-around">
                            <div class="card-deck-wrapper">
                                <div class="card-deck d-flex justify-content-around">
                                    <div class="card mb-4">
                                        <div class="view overlay">
                                            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg" alt="Card image cap">
                                            <a href="#!">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">some item</h4>
                                            <p class="card-text">
                                                <strong>Price:</strong>
                                                some price $123
                                                <br>
                                                <strong>Plaform:</strong>
                                                lazada/shopee/qoo10
                                            </p>
                                            <button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>


                                        </div>
                                    </div>

                                    <div class="card mb-4">
                                        <div class="view overlay">
                                            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/14.jpg" alt="Card image cap">
                                            <a href="#!">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">some title</h4>
                                            <p class="card-text">
                                                <strong>Price:</strong>
                                                some price $123
                                                <br>
                                                <strong>Plaform:</strong>
                                                lazada/shopee/qoo10
                                            </p>
                                            <button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
                                        </div>
                                    </div>

                                    <div class="card mb-4">
                                        <div class="view overlay">
                                            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/15.jpg" alt="Card image cap">
                                            <a href="#!">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">some title</h4>
                                            <p class="card-text">
                                                <strong>Price:</strong>
                                                some price $123
                                                <br>
                                                <strong>Plaform:</strong>
                                                lazada/shopee/qoo10
                                            </p>
                                            <button type="button" class="btn btn-yellow btn-md"><strong>Buy Now</strong></button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                    <!--/.Panel 2-->
                </div>
            </div>

        </div>

    </div>

</div>


<script>
    let sellerChart = document.getElementById('sellerChart').getContext('2d');

    // Global Options
    Chart.defaults.global.defaultFontFamily = 'Lato';
    Chart.defaults.global.defaultFontSize = 18;
    Chart.defaults.global.defaultFontColor = '#777';
    Chart.defaults.global.animation.duration = 1500;

    let myChartOne = new Chart(sellerChart, {
      type:'line', // bar, horizontalBar, pie, line, doughnut, radar, polarArea
      data:{
        labels:['Jan', 'Feb', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'Novermber', 'December'],
        datasets:[{
          label:'Searches',
          data:[
          61754,
          58045,
          65072,
          53423,
          55723,
          65623,
          74382,
          53246,
          45372,
          63619,
          43719,
          53829
          ],
          //backgroundColor:'green',
          backgroundColor:[
          'rgba(255, 148, 62, 0.5)'
          ],
          borderWidth:1,
          borderColor:'#777',
          hoverBorderWidth:3,
          hoverBorderColor:'#000'
      }]
  },
  options:{
    title:{
      display:true,
      text:'Your searches',
      fontSize:25
  },
  legend:{
      display:false,
      position:'right',
      labels:{
        fontColor:'#000'
    }
},
layout:{
  padding:{
    left:50,
    right:0,
    bottom:0,
    top:0
}
},
tooltips:{
  enabled:true
}
}
});
</script>