config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	devise_scope :user do
    	get 'users/sign_out' => "devise/sessions#destroy"
	end

	resources :queries do
		resources :results
	end
  resources :queries

  resources :results do
    resources :favourites
  end
  resources :favourites

  namespace :admin do
    resources :users do
      #view for confirmation before deletion
      get "delete"
    end
    resources :dashboards
    root 'dashboards#index'
  end

	root 'queries#index'

   #404 page. comment this to see the routing errors
   get "*any", via: :all, to: "errors#not_found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  has_one :result
end

app/models/popular_product.rb
class PopularProduct < ApplicationRecord
end

app/models/query.rb
class Query < ApplicationRecord

  belongs_to :user, optional: true
  
  validates :name, presence: true

  has_many :result
  has_many :seller_detail
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :query
  has_one :favourite
end

app/models/seller_detail.rb
class SellerDetail < ApplicationRecord
  belongs_to :query
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favourite
  has_many :query

  validates :name, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :ensure_admin_user!

	def home
	end

	private
	def ensure_admin_user!
		unless current_user and current_user.admin?
			flash[:alert] = "You don't have sufficient credentials to access this page."
			redirect_to root_path
		end
	end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :ensure_admin_user!

	def home
	end

	def ensure_admin_user!
		unless current_user and current_user.admin?
			flash[:alert] = "You don't have sufficient credentials to access this page."
			redirect_to root_path
		end
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/queries_controller.rb
require 'masterScrapper'

class QueriesController < ApplicationController
	before_action :authenticate_user!, :except => [ :index, :create, :account]
	layout "front"

	#search page
	def index
	end

	def new
		@query = Query.new
	end

	def create
		if params[:name] == ""
			flash[:notice] = "You have not entered a search query"
			return redirect_to queries_path
		end

		params[:name].downcase!

		# Query exists in the database
		if Query.find_by(name: params[:name])
			@query = Query.new
			@query.name = params[:name]
			searched_query = Query.find_by(name: params[:name])
			parsedQoo10 = Result.where(platform: 'Qoo10', query_id: searched_query.id)
			parsedLazada = Result.where(platform: 'Lazada', query_id: searched_query.id)
			parsedCarousell = Result.where(platform: 'Carousell', query_id: searched_query.id)
			@parsedAll = [{platform:'Qoo10',results:parsedQoo10},{platform:'Lazada',results:parsedLazada},{platform:'Carousell',results:parsedCarousell}]
		# Query does not exist in the database
		else
			@query = Query.new(query_params)
			@query.user_id = current_user.id if current_user
			@query.save!
			scrap = MasterScrapper.new(@query)
			@parsedAll = scrap.generate
		end
	end

	private
	def query_params
		current_user ? (params.permit(:name, current_user.id)) : (params.permit(:name))
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
	        when 'notice' then "alert alert-dismissable alert-info"
	        when 'success' then "alert alert-dismissable alert-success"
	        when 'error' then "alert alert-dismissable alert-danger"
	        when 'alert' then "alert alert-dismissable alert-danger"
	    end
	end

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def  devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    if resource.errors.full_messages.any?
        flash.now[:error] = resource.errors.full_messages
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/admins/home.html.erb
<h1>Admin Dashboard</h1>
<p>Find me in app/views/admins/home.html.erb</p>

<%= link_to 'Home', queries_path %>

app/views/layouts/_error.html.erb
<% flash.each do |key, value| %>
    <% if value.class == Array %>
        <div class="<%= flash_class(key) %>">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <% value.each do |message| %>  
                <%= message %>
                </br>
            <% end %>
        </div>
    <% else %>
        <div class="<%= flash_class(key) %>">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= value %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer">
	<!--Footer Links-->
	<div class="container">
		<div class="row index-logo align-items-center">
			<div class="logos col-lg-2 offset-lg-3">
				<%= image_tag 'Qoo10.png', height: '40', width: '100' %>
			</div>
			<div class="logos col-lg-2">
				<%= image_tag 'lazada.png', height: '30', width: '80' %>
			</div>
			<div class="logos col-lg-2">
				<%= image_tag 'carousell.png', height: '30', width: '150' %>
			</div>
		</div>
	</div>
	<!--/.Footer Links-->
</footer>
<!--/.Footer-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top scrolling-navbar">
	<a class="navbar-brand" href="/"><%= image_tag "logo.png",:size => "110x60" %></a>
	<a id="navbar_text" href="/">PRICE COMPARE</a>	
	<%= form_with scope: :query, url: queries_path,class:"form-inline" do |form| %>
		<%= text_field_tag(:name,"",:class => "form-control input-lg", placeholder: "I'm looking for ...",:id => "navbar_input") %>
		<%= submit_tag("SEARCH",:id => "navbar_submit") %>
	<% end %>
	<button id="navbar_loader"></button>
	<ul class="navbar-nav ml-auto">
		<% if user_signed_in? %>
			<li class="nav-item"><a class="nav-link navbar_links" href="/">HOME <span class="sr-only">(current)</span></a></li>
			<li class="nav-item"><%= link_to 'FAVOURITES', favourites_path,:class=>"nav-link navbar_links" %></li>
			<% if current_user.admin? %>	
				<li class="nav-item"><%= link_to 'ADMIN', admin_root_path,:class=>"nav-link navbar_links" %></li>
			<% end %>
			<li class="nav-item"><%= link_to 'SIGN OUT', destroy_user_session_path,:class=>"nav-link navbar_links" %></li> 
		<% end %>		
	</ul>	
	<div class="fixed-top" id="navbar_line"></div>	
</nav> 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>         
    <title>Project3Wdi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'admin/admin', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'admin/admin', 'data-turbolinks-track': 'reload' %>   
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project3Wdi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
    <%= stylesheet_link_tag 'front/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" 
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'front/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= render "layouts/header" %>
      <div id="mainWrapper">
        <%= render "layouts/error" %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>